In [ ]:
# Load required libraries
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import numpy as np

In [ ]:
# Load the iris dataset
iris = datasets.load_iris()
# Create our X and y data
X = iris.data
y = iris.target
print(X)

In [ ]:
print(y)

In [ ]:
# Split the data into 70% training data and 30% test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [ ]:
# Create a perceptron object with the parameters: 40 iterations (epochs) over the data, and a learning rate of 0.1
ppn = Perceptron(max_iter=100, eta0=0.1, random_state=0)
# Train the perceptron
ppn.fit(X_train, y_train)
print(ppn.coef_)
print(ppn.intercept_)

[[ 0.22  0.52 -0.72 -0.36]
 [ 1.49 -4.16  1.26 -3.72]
 [-3.47 -2.53  4.44  3.82]]
[ 0.1  1.8 -2. ]


In [ ]:
# Apply the trained perceptron on the X data to make predicts for the y test data
y_pred = ppn.predict(X_test)

In [ ]:
print(y_pred)
print(y_test)

[0 1 2 1 0 0 0 1 1 2 0 0 0 0 2 0 0 0 1 0 1 2 2 0 2 1 0 2 0 2 0 2 1 0 1 1 0
 0 2 1 0 0 1 0 0]
[0 1 2 1 0 0 0 1 2 2 1 0 0 1 2 1 0 0 2 2 2 2 2 0 2 2 0 2 0 2 0 2 1 1 1 2 0
 0 2 1 1 1 1 0 2]


In [ ]:
print('Accuracy: %.2f' % accuracy_score(y_test, y_pred))

Accuracy: 0.71


In [ ]:
confusion_matrix(y_test, y_pred)

array([[15,  0,  0],
       [ 6,  7,  0],
       [ 2,  5, 10]])

In [ ]:
confusion_matrix(y_test, y_pred,normalize='true')

array([[1.        , 0.        , 0.        ],
       [0.46153846, 0.53846154, 0.        ],
       [0.11764706, 0.29411765, 0.58823529]])

In [ ]:
confusion_matrix(y_test, y_pred,normalize='all')

array([[0.33333333, 0.        , 0.        ],
       [0.13333333, 0.15555556, 0.        ],
       [0.04444444, 0.11111111, 0.22222222]])

In [ ]:
confusion_matrix(y_test, y_pred,normalize='pred')

array([[0.65217391, 0.        , 0.        ],
       [0.26086957, 0.58333333, 0.        ],
       [0.08695652, 0.41666667, 1.        ]])